title: Nguyễn Đan Thục Khanh
logo: 
description: A passionate, detail-oriented supply chain officer who is transitioning herself into data science and analytics field, currently seeking for a data analytics role to leverage technical skills and business acumen
theme: jekyll-theme-minimal
